spring.application.name=render-example
# Database Configuration
spring.datasource.url=jdbc:postgresql://teste_example_user:ASE2fkHPzm4XKBa0KGH85IrCC27cXe2r@dpg-d7v4oposfn5c73dct030-a.frankfurt-postgres.render.com/teste_example?ssl=true&sslmode=require

spring.datasource.username=teste_example_user
spring.datasource.password=ASE2fkHPzm4XKBa0KGH85IrCC27cXe2r

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Optional: Connection pool settings
spring.datasource.hikari.maximum-pool-size=10