spring.application.name=render-example

# Server Configuration
server.port=8080
server.servlet.context-path=/

# Database Configuration (Local PostgreSQL)
spring.datasource.url=jdbc:postgresql://dpg-d7v4oposfn5c73dct030-a.frankfurt-postgres.render.com/teste_example?ssl=true&sslmode=require
spring.datasource.username=teste_example_user
spring.datasource.password=ASE2fkHPzm4XKBa0KGH85IrCC27cXe2r
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# Connection pool settings
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=20000

# Logging Configuration
logging.level.root=INFO
logging.level.com.render.example.render_example=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n

# Error handling
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
server.error.include-exception=true
